// src/types/database.types.ts
// ---------------------------------------------------------------------------
// Placeholder — replace with types generated by the Supabase CLI:
//
//   npx supabase gen types typescript \
//     --project-id <YOUR_PROJECT_ID> \
//     --schema public \
//     > src/types/database.types.ts
//
// Or via the linked local Supabase instance:
//
//   npx supabase gen types typescript --local > src/types/database.types.ts
// ---------------------------------------------------------------------------

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      // -----------------------------------------------------------------------
      // profiles — one row per auth.users row.
      // Role controls which UI shell the user lands in after login.
      // -----------------------------------------------------------------------
      profiles: {
        Row: {
          id: string; // FK → auth.users.id
          full_name: string | null;
          role: "super_admin" | "sales_supervisor" | "sales_person" | "distributor";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          role: "super_admin" | "sales_supervisor" | "sales_person" | "distributor";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          role?: "super_admin" | "sales_supervisor" | "sales_person" | "distributor";
          updated_at?: string;
        };
      };

      // -----------------------------------------------------------------------
      // orders — TODO: expand columns to match your schema
      // -----------------------------------------------------------------------
      orders: {
        Row: {
          id: string;
          distributor_id: string;
          status: "pending" | "confirmed" | "dispatched" | "delivered" | "cancelled";
          total: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          distributor_id: string;
          status?: "pending" | "confirmed" | "dispatched" | "delivered" | "cancelled";
          total: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: "pending" | "confirmed" | "dispatched" | "delivered" | "cancelled";
          total?: number;
          updated_at?: string;
        };
      };
    };

    Views: {
      [_ in never]: never;
    };

    Functions: {
      [_ in never]: never;
    };

    Enums: {
      user_role: "super_admin" | "sales_supervisor" | "sales_person" | "distributor";
      order_status: "pending" | "confirmed" | "dispatched" | "delivered" | "cancelled";
    };
  };
}
