// src/app/layout.tsx
// ---------------------------------------------------------------------------
// Root layout — applies to every route in the app.
// Loads the Geist font (variable font, both sans and mono), sets global CSS
// variables used by shadcn/ui, and wraps the tree in the Tailwind base class.
// ---------------------------------------------------------------------------

import type { Metadata, Viewport } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "TopNTown DMS",
    template: "%s | TopNTown DMS",
  },
  description: "Distribution Management System — TopNTown",
  manifest: "/manifest.json", // generated by next-pwa in production
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "TopNTown DMS",
  },
  formatDetection: {
    telephone: false,
  },
};

export const viewport: Viewport = {
  themeColor: "#2563eb",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      // Attach Geist CSS variables to :root so Tailwind + shadcn can consume them.
      className={`${GeistSans.variable} ${GeistMono.variable}`}
      suppressHydrationWarning
    >
      <body className="min-h-screen bg-background font-sans antialiased">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
