// src/middleware.ts
// ---------------------------------------------------------------------------
// Next.js Middleware — runs on every matched request in the Edge Runtime.
// Delegates to the Supabase SSR helper which refreshes the session cookie
// and enforces route protection rules.
// ---------------------------------------------------------------------------

import { type NextRequest } from "next/server";
import { updateSession } from "@/lib/supabase/middleware";

export async function middleware(request: NextRequest) {
  return await updateSession(request);
}

export const config = {
  matcher: [
    /*
     * Match all request paths EXCEPT:
     *  - _next/static  (static files)
     *  - _next/image   (image optimisation)
     *  - favicon.ico
     *  - public assets (sw.js, workbox-*, manifest.json generated by next-pwa)
     */
    "/((?!_next/static|_next/image|favicon.ico|sw.js|workbox-.*|manifest.json|icons/).*)",
  ],
};
